DROP TABLE IF EXISTS SALE;
DROP TABLE IF EXISTS GOODS;

CREATE TABLE GOODS(
	ID int(11),
	NAME VARCHAR(100),
	AMOUNT int(11),
	PRICE DOUBLE(7,2)
	);

CREATE TABLE SALE(
	ID int(11) primary key auto_increment,
	GID int(11),
	NUM int(11)
	);



INSERT INTO GOODS ( ID, NAME, AMOUNT, PRICE) VALUES ( 
1001, 'LAPTOP', 100, 6000); 
INSERT INTO GOODS ( ID, NAME, AMOUNT, PRICE) VALUES ( 
1002, 'MOBILE', 50, 3000); 
commit;
